### ISSUE TITLE
A suggestion to update the minSdk

### ISSUE THREAD

**Issue by Husseinhj** [techinessoverloaded/progress-dialog#24]
Is there any particular reason for adding `minSdk = 24`?

The application worked with `minSdk = 21`. Is it possible to change the `minSdk` version?

**Comment by techinessoverloaded** [comment]
> Is there any particular reason for adding `minSdk = 24`?
> 
> The application worked with `minSdk = 21`. Is it possible to change the `minSdk` version?

Hi, The main reason why `24` was chosen as the `minSdk` version is because, some Android SDK Components which are used in the library have a `minSdk` version of `23` or so. And also, Android's own `ProgressDialog` component was depcrecated in API Level `26` and hence my aim was to offer a similar component to Android developers, and hence I kept the `minSdk` as `24`, which is 2 versions ahead of `26`.

**Comment by techinessoverloaded** [comment]
I do find it odd to know that it is working in API Level `21`. I will check if I had declared the `minSdk = 24` in the wrong place. A library module works differently as compared to App module. But, I would still recommend you to use it in apps which have `minSdk` as `24` or above, in order to avoid bugs.
